package errhandling

import "testing"

func Test_customErrorDemo(t *testing.T) {
	t.Helper()

	customErrorDemo()
}
